rules = [
  CompareSameValue
  DirectoryAndPackageName
  DuplicateWildcardImport
  EnumUnnecessaryExtends
  FileNameConsistent
  IncorrectScaladocParam
  InterpolationToStringWarn
  UnmooredDocComment
  UnusedTypeParams
  UselessParamCommentsWarn
  UsingParamAnonymous
  UsingParamAnonymousConstructor
]

lint.error = {
  includes = ".*"
  excludes = "UnusedScalafixSuppression"
}
